# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: tpss-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: tpss-app
#   template:
#     metadata:
#       labels:
#         app: tpss-app
#     spec:
#       containers:
#         - name: tpss-app
#           image: courageoi/nodeapp:1.0
#           ports:
#           - containerPort: 3001
#           resources:
#             requests:
#               cpu: "0.5"
#               memory: "500Mi"
#             limits:
#               cpu: "1"
#               memory: "1Gi"
        
---
apiVersion: v1
kind: Service
metadata:
  name: tpss-app-service-stable
spec:
  selector:
    app: tpss-rollout-demo
  ports:
    - name: http
      port: 80
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: tpss-app-service-canary
spec:
  selector:
    app: tpss-rollout-demo
  ports:
    - name: http
      port: 80
      targetPort: 3001

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: tpss-rollout-demo
spec:
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 80
      # Reference to a Service which the controller will update to point to the canary ReplicaSet
      canaryService: tpss-app-service-canary
      # Reference to a Service which the controller will update to point to the stable ReplicaSet
      stableService: tpss-app-service-stable
  selector:
    matchLabels:
      app: tpss-rollout-demo
  template:
    metadata:
      labels:
        app: tpss-rollout-demo
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 3001
          resources:
            requests:
              cpu: "0.5"
              memory: "500Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-tpss-rollout-demo
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: tpss-rollout-demo
  targetCPUUtilizationPercentage: 80